import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
const validation = await readFile(new URL("../VALIDATION.md", import.meta.url), "utf8");
const proofText = await readFile(new URL("../proofs/x402-search-2026-09-04.json", import.meta.url), "utf8");
const proof = JSON.parse(proofText);
const synthesisProofText = await readFile(new URL("../proofs/x402-synthesis-2026-09-04.json", import.meta.url), "utf8");
const synthesisProof = JSON.parse(synthesisProofText);
assert.match(readme, /curl[^\n]+https:\/\/aggregator-beta\.vercel\.app\/api\/sample\?q=/, "README must include a one-command production free trial");
assert.match(readme, /https:\/\/aggregator-beta\.vercel\.app\/mcp/, "README must show the exact remote MCP endpoint");
assert.match(readme, /VALIDATION\.md/, "README must link the public validation baseline");
assert.match(readme, /experimental/i, "README must label the service honestly during validation");
assert.match(readme, /operator-funded signed `PAYMENT-SIGNATURE` search purchase[^\n]+verified/i, "README must record canonical signed settlement proof");
assert.match(readme, /0x05d41f696732284339130d869cdc84b0d259f5122b9d61212bcd083675952555/i, "README must link the signed-settlement transaction");
assert.doesNotMatch(readme, /has not yet been independently verified/i, "README must not retain obsolete pending-settlement wording");
assert.match(readme, /no external paid demand/i, "README must not imply commercial validation");
assert.match(validation, /301 total telemetry events/i, "validation baseline must publish the exact event count");
assert.match(validation, /0 externally paid calls/i, "validation baseline must disclose zero external revenue");
assert.match(validation, /operator-funded signed x402 search purchase/i, "validation must record the signed purchase without counting it as demand");
assert.match(validation, /0x05d41f696732284339130d869cdc84b0d259f5122b9d61212bcd083675952555/i, "validation must publish the signed-settlement transaction");
assert.match(validation, /operator-funded signed x402 synthesis purchase/i, "validation must record the synthesis proof without counting it as demand");
assert.match(validation, /0x67bae3bafd3e93ec671a2ec516b3ac3826603938d8518a18b97dc221e3eadc9a/i, "validation must publish the synthesis-settlement transaction");
assert.match(validation, /2026-09-06T11:22:00Z/, "validation baseline must publish the fixed decision time");
assert.equal(proof.schema, "supersignal/x402-level4-proof/v1");
assert.equal(proof.proofLevel, 4);
assert.equal(proof.operatorFunded, true);
assert.equal(proof.externalDemand, false);
assert.equal(proof.initialStatus, 402);
assert.equal(proof.paidStatus, 200);
assert.equal(proof.settlementSuccess, true);
assert.equal(proof.transaction, "0x05d41f696732284339130d869cdc84b0d259f5122b9d61212bcd083675952555");
assert.equal(proof.amountUsdc, "0.02");
assert.equal(proof.transferLogVerified, true);
assert.equal(proof.output?.resultCount, 8);
assert.doesNotMatch(proofText, /private.?key|payment-signature|\"signature\"/i, "public proof must contain no signing secret or reusable authorization");
assert.equal(synthesisProof.schema, "supersignal/x402-level4-proof/v1");
assert.equal(synthesisProof.proofLevel, 4);
assert.equal(synthesisProof.operatorFunded, true);
assert.equal(synthesisProof.externalDemand, false);
assert.equal(synthesisProof.initialStatus, 402);
assert.equal(synthesisProof.paidStatus, 200);
assert.equal(synthesisProof.settlementSuccess, true);
assert.equal(synthesisProof.transaction, "0x67bae3bafd3e93ec671a2ec516b3ac3826603938d8518a18b97dc221e3eadc9a");
assert.equal(synthesisProof.amountUsdc, "0.1");
assert.equal(synthesisProof.transferLogVerified, true);
assert.equal(synthesisProof.output?.angleCount, 3);
assert.equal(synthesisProof.output?.totalSources, 15);
assert.doesNotMatch(synthesisProofText, /private.?key|payment-signature|\"signature\"/i, "public synthesis proof must contain no signing secret or reusable authorization");
console.log("PASS public docs provide an exact free trial, MCP endpoint, and honest validation baseline");
